# Generated by Django 4.1.2 on 2023-09-25 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
