# Generated by Django 4.2.5 on 2023-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_delete_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
        ),
    ]
